### ISSUE TITLE
build.sh points to the wrong directory

### ISSUE THREAD

**Issue by luigimannoni** [zaphot/docker-elysium#1]
`cd /usr/src/data/source/server/build` should point instead to `cd /usr/src/data/source/server/cmake`

**Comment by zaphot** [comment]
Ah sry, i forgot to create this folder if it's not existing. i followed roughly what they describe in their https://github.com/elysium-project/server/blob/development/.travis.yml 
They created this separate build folder which is in .gitignore and thus not there by default. 

Unfortunately they changed their database repository and i need to adjust some parts in the script. However the migrations are currently a mess, see https://github.com/elysium-project/database/issues/38
When they fix it,i will fix the script.

**Comment by zaphot** [comment]
Since they fixed the db issue, i updated the build.sh file to the new elysium git structure. Moreover the build folder will now be created if its not there. So this should be fixed. Thanks for reporting!
